// Ant Design Vue
import {
  Alert,
  AutoComplete,
  Badge,
  Button,
  Divider,
  Breadcrumb,
  Calendar,
  Card,
  Carousel,
  Collapse,
  DatePicker,
  Drawer,
  Dropdown,
  List,
  Input,
  InputNumber,
  Checkbox,
  Radio,
  Rate,
  Form,
  Select,
  Slider,
  Switch,
  Skeleton,
  Spin,
  Space,
  Steps,
  TimePicker,
  Tag,
  Tabs,
  Table,
  Tooltip,
  Timeline,
  Modal,
  Menu,
  Progress,
  Pagination,
  Row,
  Col,
  Popover,
  Popconfirm,
} from "ant-design-vue";

export const load_components = (app: any) => {
  app.component(Alert);
  app.component(AutoComplete);
  app.component(Badge);
  app.component(Button);
  app.component(Divider);
  app.component(Breadcrumb);
  app.component(Calendar);
  app.component(Card);
  app.component(Carousel);
  app.component(Collapse);
  app.component(DatePicker);
  app.component(Dropdown);
  app.component(Drawer);
  app.component(List);
  app.component(Input);
  app.component(InputNumber);
  app.component(Checkbox);
  app.component(Radio);
  app.component(Rate);
  app.component(Form);
  app.component(Select);
  app.component(Slider);
  app.component(Switch);
  app.component(Skeleton);
  app.component(Spin);
  app.component(Space);
  app.component(Steps);
  app.component(TimePicker);
  app.component(Tag);
  app.component(Tabs);
  app.component(Table);
  app.component(Tooltip);
  app.component(Timeline);
  app.component(Modal);
  app.component(Menu);
  app.component(Progress);
  app.component(Pagination);
  app.component(Row);
  app.component(Col);
  app.component(Popover);
  app.component(Popconfirm);
};
